### ISSUE TITLE
Error in connecting Arduino to GAMA

### ISSUE THREAD

**Issue by NaroaCS** [CityScope/FoodDeliveries#1]
Hello @agrignard,
Speaking from a City Scope repo now ;) We have been updating the info on this issue in the Gama github ([here](https://github.com/gama-platform/gama/issues/3588))
We'd really appreciate any help on this !

**Comment by agrignard** [comment]
As reported in the GAMA Github today by @hqnghi88, can you try with the last alpha version (GAMA 1.9.0 alpha) https://github.com/gama-platform/gama/releases/tag/1.9.0

Also have you tried the exemple to test that your UDP protocol is working? To do so you can run the following models Network/Available Protocols/UDP Protocol/UDP Listener Mouse from Processing.gaml and tun the Processing script in parallel. This exemple is a hello world to show how GAMA and another software (in this case Processing) can communicate through UDP.

**Comment by ainhoagenua** [comment]
Hi @agrignard !

I have just tried the new alpha release but the error remains the same...

![JavaError - NoClassDefFoundError](https://user-images.githubusercontent.com/101112352/217324312-e35027df-4ad1-43d8-8090-57c1881a5c73.png)

I also tried the example you mentioned to test my UDP control, and it is perfectly working.

**Comment by agrignard** [comment]
Ok so in this case I am not sure this is related to GAMA itself but maybe to your arduino script. The processing exemple is making the link between GAMA and Processing through UDP. But in your arduino script are you using another protocol? I guess you are using just a serialisation right (no way to use UDP directly in arduinoi?)?

It will be difficult for me and/or the Gama team to test it as we do not have the arduino hardware neither the script (BTW that something you could push in the github so I can try to replicate it (but I will need the script and the exact list of hardware you are using to see if I can purchase it). What's for sure it has already been implemented and working  in different project (e.g on a demo that was running in the lab with a slider controlling a parameter of the Gama simulation. You can have a look at the working code in this repo https://github.com/CityScope/CSL_Hanoi)

One thing I don't get in this issue https://github.com/gama-platform/gama/issues/3588 is the point 6 "Exit Arduino application" are you sure you need to exit the application? Shouldn't it be running in parallel? Also you get this error "Error Connecting, Try Another Port" did you try different port? Are you sure your computer is giving access to this port? 

A second thought to make your demo working and also to be sure your arduino script is working:

Try to make your arduino script communicate with processing with the serial port and then plug processing and GAMA with UPD. I know it's one software more to implement and to launch but at least you will be able to control something in GAMA with your arduino (through processing) and move forward with your demo until we found and fix your bug.

**Comment by hqnghi88** [comment]
sorry, my bad, missed export a library, please retry once more the alpha release

**Comment by ainhoagenua** [comment]
Hi @agrignard and @hqnghi88 !

I finally managed to connect Arduino to Gama through Processing.

However, connecting Arduino to GAMA directly following the example that can be found in "Plugin models/Network/2 Available protocols/Arduino" did not work (not even with the latest release of the alpha version). Trying to do so, I always get the same error message... I have tried with different ports, different computers (Windows and Mac), exiting and not exiting the Arduino application..., but the error is always the same.

As mentioned before, I followed your recommendation and managed to make the Arduino script communicate with Processing with the serial port and then plug Processing and GAMA with UPD.

Thank you for your help once again!

**Comment by hqnghi88** [comment]
Hi, i tested on mac m1 and it should not have "not found class" message witj the latest alpha. However i cant test on win for the moment and as Arnaud said we dont have always the arduino boards. We will try to  investigate in occasion

**Comment by agrignard** [comment]
@ainhoagenua good to know at least you can move forward in your demo with the Processing bridge. However we still need to investigate what is wrong with this arduino bridge as this is a feature should work on a GAMA point of view especially as it used to work). So we will need your help on this

@hqnghi88 do you have any idea why it is not working for @ainhoagenua 
@ainhoagenua to dig more this issue can you describe a more in details the process and workflow you are using (which model, which experiment you are launching so we can try to replicate it on our side.)

**Comment by ainhoagenua** [comment]
Hi @agrignard and @hqnghi88 !

This is the detailed description of the components and process I am using to test the Arduino-GAMA connection:

- Laptop with the following Windows specifications: Edition: Windows 11 Home, Version: 22H2.
- Latest alpha version of GAMA.
- Process:
  1. Connect one slider to an Arduino Nano.
  2. Connect the Arduino to a laptop port.
  3. Open GAMA application.
  4. Go to Plugin models, then Network, then 2 Available protocols.
  5. Click on Arduino.
  6. Open .ino file (inside of Arduino script/slider_code_01/) and upload information to the Arduino Nano.
  7. Confirm readability of slider in Serial Monitor.
  8. Exit Arduino application.
  9. Open Arduino Listener.gaml model back in GAMA.
  10. Run the test_Arduino experiment
  11. Error Connecting: Try another port.

![Arduino-GAMA error](https://user-images.githubusercontent.com/101112352/217848801-d0b10252-b601-4ce6-b4d7-1d2208111c1f.png)

**Comment by agrignard** [comment]
@hqnghi88 thank for you help. To facilitate the process can you  explain to @ainhoagenua how to launch the gaml model in in terminal/console mode

**Comment by hqnghi88** [comment]
<img width="583" alt="Screenshot 2023-02-09 at 22 58 08" src="https://user-images.githubusercontent.com/6105384/217866461-fe527c5e-5b2c-482d-9425-f20c42922566.png">
In fact, you can check it in Arduino IDE (long time no playing with that so in theory, it is in Serial Port menu)

**Comment by hqnghi88** [comment]
<img width="684" alt="Screenshot 2023-02-10 at 20 56 01" src="https://user-images.githubusercontent.com/6105384/218109323-748e7f18-15e4-48af-9fe9-3c4707b11cc2.png">
I add the possibility to declare the name of serial port, once you check its in arduino IDE, change the facet "to" of the connect statement as in screenshot (of course only in the latest alpha binary).

**Comment by ainhoagenua** [comment]
Hi @hqnghi88 !

I tried to check in Arduino IDE the serial port and the menu looks quite different:

![Arduino IDE](https://user-images.githubusercontent.com/101112352/218117585-3a13c8a7-355e-4bb2-832b-ebea82a88729.png)

From this, I understand that my port is "COM4", so I wrote the following in the latest alpha version after exiting Arduino IDE:

![GAMA](https://user-images.githubusercontent.com/101112352/218117919-e0653ee9-2472-410f-bbbd-071baf137a34.png)

When I run the test_Arduino experiment in the Arduino Listener model, the error remains the same:

![Error](https://user-images.githubusercontent.com/101112352/218118465-c3992877-3bad-4376-935a-792bf2a18016.png)

I would appreciate if you could give me instructions on how to launch the experiment on the terminal to verify if I get that code line or not.

Thank you for your help!

**Comment by hqnghi88** [comment]
The release compilation is not finish redownload when this release is named with 12097d41
https://github.com/gama-platform/gama/releases/tag/1.9.0

**Comment by hqnghi88** [comment]
if you are on win, launch cmd, change dir to where you have gama.exe, then launch gama.exe -c it will show all the messages in console

**Comment by hqnghi88** [comment]
It finished, you can download and retry

**Comment by ainhoagenua** [comment]
Hi @hqnghi88 !

I am not able to launch the new alpha version in my laptop... It says "GAMA is not responding"

**Comment by hqnghi88** [comment]
try new workspace, the code base is not changed too much so it should be the caches/metadata problem, i think

**Comment by ainhoagenua** [comment]
Still not responding...

**Comment by agrignard** [comment]
@ainhoagenua do you have any update on this issue? Were you able to test with the new Gama 1.0 last release? I personally do not have any issue launching it. What is your computer simualtion configuration so far? Did you download the version with JDK included?

**Comment by ainhoagenua** [comment]
Hi @hqnghi88 and @agrignard !

Good news! I tried to download and launch the latest alpha version of GAMA and it worked. 

It took a couple of minutes but is finally working!

I also managed to connect the Arduino directly to GAMA using the new attribute "to:" in the Arduino protocol.

Thank you so much for your help once again!

**Comment by agrignard** [comment]
Ok that's good to hear and so we can close this issue.

So a big thank you to @hqnghi88 for his help and looking forward to seeing more how your demo is looking like now that the bridge is done.
